#!/bin/bash
#
# Title:      PTS Install base
# Author(s):  MrDoobPG
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Cloning PTS - From Installer
      git:
        repo: 'https://github.com/PTS-Team/PTS-Team'
        dest: /opt/plexguide
        clone: yes
        version: master
        force: yes
        update: yes
      become: yes
      ignore_errors: yes

    - stat:
        path: /opt/plexguide
      register: p
    - debug:
        msg: "Path exists and is a directory"
      when: p.stat.isdir is defined and p.stat.isdir