#!/bin/bash
#
# Title:      PTS Install base
# Author(s):  MrDoobPG
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Cloning PTS - From Installer
      git:
        repo: 'https://github.com/PTS-Team/PTS-Team'
        dest: /opt/plexguide
        version: 'master'
        force: yes
      ignore_errors: yes
